apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: {{ include "lagoon-logging.fullname" . }}
  labels:
    {{- include "lagoon-logging.labels" . | nindent 4 }}
spec:
  fluentd: {}
  fluentbit: {}
  controlNamespace: {{ .Release.Namespace | quote }}
