apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lagoon-logging.logsDispatcher.fullname" . }}-env
  labels:
    {{- include "lagoon-logging.logsDispatcher.labels" . | nindent 4 }}
data:
  CLUSTER_NAME: >-
    {{ required "A valid .Values.clusterName required!" .Values.clusterName }}
  LOGS_FORWARD_HOST: >-
    {{ required "A valid .Values.forward.host required!" .Values.forward.host }}
  LOGS_FORWARD_HOSTNAME: >-
    {{ coalesce .Values.forward.hostName .Values.forward.host }}
  LOGS_FORWARD_HOST_PORT: >-
    {{ default "24224" .Values.forward.hostPort }}
