apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lagoon-logs-concentrator.fullname" . }}-fluent-conf
  labels:
    {{- include "lagoon-logs-concentrator.labels" . | nindent 4 }}
data:
  fluent.conf: |
    # vi: ft=fluentd
    <system>
      workers 4
    </system>
    <source>
      # fluentd parameters
      @type forward
      @id   in_forward
      <security>
        self_hostname logs-concentrator
        user_auth true
        @include user.d/*.conf
      </security>
      <transport tls>
        ca_path /fluentd/tls/ca.crt
        cert_path /fluentd/tls/server.crt
        private_key_path /fluentd/tls/server.key
        client_cert_auth true
      </transport>
    </source>
    # send to elasticsearch
    <match **>
      @type elasticsearch
      @id out_elasticsearch
      # ingestion
      target_index_key index_name
      include_timestamp true
      time_key time
      # endpoint
      host "#{ENV['ELASTICSEARCH_HOST']}"
      port "#{ENV.fetch('ELASTICSEARCH_HOST_PORT','9300')}"
      scheme "#{ENV.fetch('ELASTICSEARCH_SCHEME','http')}"
      ssl_min_version TLSv1_2
      ssl_max_version TLSv1_3
      user admin
      password "#{ENV['LOGSDB_ADMIN_PASSWORD']}"
      # endpoint error handling
      reconnect_on_error true
      reload_on_failure true
      request_timeout 600s
      slow_flush_log_threshold 300s
      # buffer chunks by tag
      <buffer tag>
        @type file
        path /fluentd/buffer/elasticsearch
        # buffer params (per worker)
        total_limit_size 8GB
        # flush params
        flush_thread_count 4
        overflow_action drop_oldest_chunk
      </buffer>
      # silence warnings (these have no effect)
      type_name _doc
      ssl_version TLSv1_2
    </match>
