apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lagoon-logs-concentrator.fullname" . }}-env
  labels:
    {{- include "lagoon-logs-concentrator.labels" . | nindent 4 }}
stringData:
  LOGSDB_ADMIN_PASSWORD: {{ required "A valid .Values.elasticsearchAdminPassword required!" .Values.elasticsearchAdminPassword }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lagoon-logs-concentrator.fullname" . }}-tls
  labels:
    {{- include "lagoon-logs-concentrator.labels" . | nindent 4 }}
stringData:
  ca.crt: {{ required "A valid .Values.tls.caCert required!" .Values.tls.caCert }}
  server.crt: {{ required "A valid .Values.tls.serverCert required!" .Values.tls.serverCert }}
  server.key: {{ required "A valid .Values.tls.serverKey required!" .Values.tls.serverKey }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lagoon-logs-concentrator.fullname" . }}-users
  labels:
    {{- include "lagoon-logs-concentrator.labels" . | nindent 4 }}
stringData:
  user.conf: |
    {{- range .Values.users }}
    <user>
      username "{{ .username }}"
      password "{{ .password }}"
    </user>
    {{- end }}
