apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lagoon-logs-concentrator.fullname" . }}-env
  labels:
    {{- include "lagoon-logs-concentrator.labels" . | nindent 4 }}
stringData:
  LOGSDB_ADMIN_PASSWORD: {{ required "A valid .Values.elasticsearchAdminPassword required!" .Values.elasticsearchAdminPassword }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lagoon-logs-concentrator.fullname" . }}-tls
  labels:
    {{- include "lagoon-logs-concentrator.labels" . | nindent 4 }}
stringData:
  LOGSDB_ADMIN_PASSWORD: {{ required "A valid .Values.elasticsearchAdminPassword required!" .Values.elasticsearchAdminPassword }}
